# -*- coding: utf-8 -*-
"""sorting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qz8ghteAvO4fOx3QAHz__80fDy45YaeW
"""



"""I just need more time to understand."""