# -*- coding: utf-8 -*-
"""reverse_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AbGe0oEySC9ZocMhIa_r4xTbgu9frW4m
"""

# creating function reverse_array(A)
def reverse_array(A):
  # reversing the array
  return A[::-1]

# testing the function with th array
A = [10, 5, 6, 9]
print('Reversed array: ',reverse_array(A))

