# -*- coding: utf-8 -*-
"""reverse_sentence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSMO2kr_F0_p1qH63t7BGd__uzlNXYlp
"""

# creating the function to reverse the words in the sentence
def reverse_sentence(A):

  # join the array into words
  join = ''.join(A)

  # print the sentence into words
  split = join.split(' ') 

  # reverse the words 
  reverse = split[::-1]
  
  # join the words into a sentence
  join_words = ' '.join(reverse)
  

  # split the sentence into characters
  return [char for char in join_words]

  
  

A = ['t','h','i','s',' ','i','s',' ','g','o','o','d']
print('Reversed sentence: ',reverse_sentence(A))

